version: '3.8'

services:
  webserver:
    networks:
      - default
    ports:
      - "0.0.0.0:8081:8080"  
    environment:
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0

  scheduler:
    networks:
      - default

  triggerer:
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    networks:
      - default

networks:
  default:
    driver: bridge
